import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { classifyCutover, sha256, snapshotDigest } from './classify_supabase_mazer_master_cutover_data_fence_r001.mjs';
import { renderOperationalSql } from './produce_supabase_mazer_master_preparation_private_source_r017.mjs';
import { CONTRACT, validatePrivateSource } from './materialize_supabase_mazer_master_preparation_r017.mjs';
import { writePrivateOutput } from './transform_supabase_mazer_master_preparation_private_delta_r017.mjs';

export const AI_RECEIPT_DELTA_CONTRACT=Object.freeze({baseSha256:'754dca84d02d7e3c67064bc4a67ddcfffea196d5990d757afd4e86bbbdea7c33',deltaSha256:'a75b481781a195cc3878a32e404f59962ac71797974acc0776451551c20e964f',observedAt:'2026-08-26T17:54:50.291Z',evidenceSha256:CONTRACT.currentPreimageSha256,successorSha256:'9326145071e2e067286e6460d06187d89d3bdc6b82c202b2cbea2f313f0b35ae'});
export const AI_RECEIPT_PRIVATE_ROOT=path.join(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),'secrets','packet','mazer-master-preparation-r017');
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
const digest=v=>sha256(Buffer.from(canonical(v)));const plain=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);const exact=(v,k)=>plain(v)&&canonical(Object.keys(v).sort())===canonical([...k].sort());const lower=v=>String(v).toLowerCase();const comparable=v=>BigInt(String(v));const unquote=v=>v.replaceAll("''", "'");const extract=(t,r,c)=>{const m=t.match(r);if(!m)throw new Error(c);return unquote(m[1]);};
function playerEnvelope(value){const row={revision:0,level_reached_at:null,...structuredClone(value)};row.player_level=String(row.player_level);row.player_completed_cycles=String(row.player_completed_cycles);if(!plain(row.state))throw new Error('PLAYER_STATE');const tracks=plain(row.state.tracks)?structuredClone(row.state.tracks):{};tracks.player={...(plain(tracks.player)?structuredClone(tracks.player):{}),level:row.player_level,completedCycles:row.player_completed_cycles};row.state={...structuredClone(row.state),tracks};return{user_id:lower(row.user_id),level:row.player_level,completed_cycles:row.player_completed_cycles,revision:Number(row.revision??0),target_complexity:Number(row.player_target_complexity),rank:row.player_rank,state_projection_matches:true,payload_digest:digest(row),row};}
function aiEnvelope(value){const row=structuredClone(value);row.level=String(row.level);row.completed_cycles=String(row.completed_cycles);if(!plain(row.state)||!plain(row.summary))throw new Error('AI_STATE');row.state={...structuredClone(row.state),level:row.level,completedCycles:row.completed_cycles};row.summary={...structuredClone(row.summary),level:row.level,completedCycles:row.completed_cycles};return{user_id:lower(row.user_id),runner_key:row.runner_key,level:row.level,completed_cycles:row.completed_cycles,target_complexity:Number(row.target_complexity),rank:row.rank,state_projection_matches:true,payload_digest:digest(row),row};}
function receiptEnvelope(value){const row={ruleset_id:null,recipe_version:null,recipe_hash:null,client_run_id:null,...structuredClone(value)};return{id:lower(row.id),user_id:lower(row.user_id),client_run_id:row.client_run_id==null?null:lower(row.client_run_id),payload_digest:digest({...row,user_id:'__mapped-owner__'}),row};}
function assertMonotonic(before,after,kind){const rank=['E','D','C','B','A','S'],prior=before.row;if(kind==='PLAYER'&&(comparable(after.player_level)<comparable(prior.player_level)||comparable(after.player_completed_cycles)<comparable(prior.player_completed_cycles)||Number(after.player_target_complexity)<Number(prior.player_target_complexity)||rank.indexOf(after.player_rank)<rank.indexOf(prior.player_rank)))throw new Error('PLAYER_MONOTONIC');if(kind==='AI'&&(comparable(after.level)<comparable(prior.level)||comparable(after.completed_cycles)<comparable(prior.completed_cycles)||Number(after.target_complexity)<Number(prior.target_complexity)||rank.indexOf(after.rank)<rank.indexOf(prior.rank)))throw new Error('AI_MONOTONIC');if(Date.parse(after.updated_at)<Date.parse(prior.updated_at))throw new Error(`${kind}_TIMESTAMP`);}

export function transformAiReceiptDelta(base,delta){
  if(!exact(delta,['schema','observed_at','proof','player_rows','ai_rows','receipt_rows'])||delta.schema!=='atlas.supabase.mazer-master-r017-progression-receipt-delta.v1')throw new Error('DELTA_SCHEMA');
  if(typeof delta.observed_at!=='string'||!Number.isFinite(Date.parse(delta.observed_at))||new Date(delta.observed_at).toISOString()!==AI_RECEIPT_DELTA_CONTRACT.observedAt)throw new Error('DELTA_OBSERVED_AT');
  const proofKeys=['ai_changed','player_changed','receipts_added','ai_owner_orphans','ai_shape_violations','player_owner_orphans','receipt_owner_orphans','ai_monotonic_violations','ai_timestamp_violations','player_shape_violations','receipt_client_run_missing','player_monotonic_violations','player_timestamp_violations','receipt_client_run_duplicates'],proof=delta.proof;
  if(!exact(proof,proofKeys)||!Array.isArray(delta.player_rows)||!Array.isArray(delta.ai_rows)||!Array.isArray(delta.receipt_rows))throw new Error('DELTA_PROOF');
  if(proof.player_changed!==12||proof.ai_changed!==14||proof.receipts_added!==1||proofKeys.slice(3).some(k=>proof[k]!==0)||delta.player_rows.length!==12||delta.ai_rows.length!==14||delta.receipt_rows.length!==1)throw new Error('DELTA_COUNTS');
  if(base.schema!==CONTRACT.schema||base.packet!==CONTRACT.packet)throw new Error('BASE_SCHEMA');
  const source=structuredClone(base.fence_input.source_snapshot),mapped=new Set(base.fence_input.identity_map.map(v=>v.legacy_user_id));let effectivePlayer=0,effectiveAi=0,resetAi=null;const seenPlayer=new Set(),seenAi=new Set();
  for(const raw of delta.player_rows){const id=lower(raw.user_id),index=source.player.findIndex(v=>v.user_id===id);if(index<0||seenPlayer.has(id)||!mapped.has(id))throw new Error('PLAYER_BINDING');seenPlayer.add(id);const before=source.player[index];if(canonical(raw)===canonical(before.row))throw new Error('PLAYER_RAW_NOOP');assertMonotonic(before,raw,'PLAYER');const after=playerEnvelope(raw);if(canonical(after.row)!==canonical(before.row)){source.player[index]=after;effectivePlayer++;}}
  for(const raw of delta.ai_rows){const id=lower(raw.user_id),key=`${id}:${raw.runner_key}`,index=source.ai.findIndex(v=>v.user_id===id&&v.runner_key===raw.runner_key);if(index<0||seenAi.has(key)||!mapped.has(id))throw new Error('AI_BINDING');seenAi.add(key);const before=source.ai[index];if(canonical(raw)===canonical(before.row))throw new Error('AI_RAW_NOOP');assertMonotonic(before,raw,'AI');const after=aiEnvelope(raw);if(canonical(after.row)!==canonical(before.row)){source.ai[index]=after;effectiveAi++;if(id===base.reset_era_ai.legacy_user_id&&raw.runner_key==='menu-runner')resetAi=after;}}
  if(effectivePlayer!==0||effectiveAi!==1||!resetAi)throw new Error(`EFFECTIVE_DELTA_${effectivePlayer}_${effectiveAi}_${Boolean(resetAi)}`);
  const receipt=receiptEnvelope(delta.receipt_rows[0]);if(!mapped.has(receipt.user_id)||!receipt.client_run_id||source.receipts.some(v=>v.id===receipt.id)||source.receipts.some(v=>v.user_id===receipt.user_id&&v.client_run_id===receipt.client_run_id)||base.fence_input.target_snapshot.receipts.some(v=>v.client_run_id===receipt.client_run_id)||Date.parse(receipt.row.completed_at)>Date.parse(resetAi.row.updated_at))throw new Error('RECEIPT_BINDING');source.receipts.push(receipt);source.ai.sort((a,b)=>canonical([a.user_id,a.runner_key]).localeCompare(canonical([b.user_id,b.runner_key])));source.receipts.sort((a,b)=>a.id.localeCompare(b.id));source.observed_at=AI_RECEIPT_DELTA_CONTRACT.observedAt;
  const fence=structuredClone(base.fence_input);fence.source_snapshot=source;fence.expected_source_high_water_digest=snapshotDigest(source);fence.zero_delta_reads=[1,2].map(ms=>({...structuredClone(source),observed_at:new Date(Date.parse(source.observed_at)+ms).toISOString()}));const classified=classifyCutover(fence);if(canonical(classified.receipt.desired_counts)!==canonical({profiles:13,player:16,ai:16,receipts:1887}))throw new Error('DELTA_DENOMINATOR');
  const reset=structuredClone(base.reset_era_ai);reset.canonical_projection='9/8/40/D';reset.legacy_receipts=1716;reset.canonical_row_digest=digest(resetAi);const action=structuredClone(fence),targetIndex=action.target_snapshot.ai.findIndex(v=>v.user_id===reset.master_user_id&&v.runner_key==='menu-runner');if(targetIndex<0)throw new Error('RESET_TARGET');const mappedAi=structuredClone(resetAi);mappedAi.user_id=reset.master_user_id;mappedAi.row.user_id=reset.master_user_id;mappedAi.payload_digest=digest(mappedAi.row);action.target_snapshot.ai[targetIndex]=mappedAi;
  const quarantineKey=extract(base.sql['reset-era-apply.sql'],/pgp_sym_encrypt\('(?:''|[^'])*','((?:''|[^'])*)','cipher-algo=aes256'\)/,'QUARANTINE_KEY_PARSE'),qaPassword=extract(base.sql['qa-apply.sql'],/extensions\.crypt\('((?:''|[^'])*)',extensions\.gen_salt\('bf'\)\)/,'QA_PASSWORD_PARSE');const rendered=renderOperationalSql({auth:base.auth,fenceInput:fence,actionFenceInput:action,catalogPreimage:base.catalog_preimage,reset:{quarantined_row:reset.quarantined_row},qa:base.qa,quarantineKey,qaPassword});const out={...structuredClone(base),evidence:{...base.evidence,current_preimage_sha256:CONTRACT.currentPreimageSha256},fence_input:fence,reset_era_ai:reset,sql:rendered.sql,sql_sha256:rendered.sql_sha256};validatePrivateSource(out);return out;
}
export function writeAiReceiptPrivateOutput(outputPath,bytes){writePrivateOutput(outputPath,bytes,AI_RECEIPT_PRIVATE_ROOT);}
export function transformAiReceiptFiles(basePath,deltaPath,outputPath){const baseBytes=fs.readFileSync(basePath),deltaBytes=fs.readFileSync(deltaPath);if(sha256(baseBytes)!==AI_RECEIPT_DELTA_CONTRACT.baseSha256||sha256(deltaBytes)!==AI_RECEIPT_DELTA_CONTRACT.deltaSha256)throw new Error('INPUT_SHA');const out=transformAiReceiptDelta(JSON.parse(baseBytes),JSON.parse(deltaBytes));const bytes=Buffer.from(`${canonical(out)}\n`);if(sha256(bytes)!==AI_RECEIPT_DELTA_CONTRACT.successorSha256)throw new Error('SUCCESSOR_SHA');writeAiReceiptPrivateOutput(outputPath,bytes);return{path:path.resolve(outputPath),sha256:sha256(bytes),bytes:bytes.length};}
const isMain=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);if(isMain){try{const r=transformAiReceiptFiles(process.argv[2],process.argv[3],process.argv[4]);console.log(JSON.stringify({result:'PASS_R017_AI_RECEIPT_PRIVATE_DELTA_TRANSFORMED',private_source_sha256:r.sha256,private_source_bytes:r.bytes,raw_private_output:false}))}catch(error){console.log(JSON.stringify({result:'HOLD_R017_AI_RECEIPT_PRIVATE_DELTA_TRANSFORM',category:String(error.message).replace(/[^A-Za-z0-9_:.-]/g,''),raw_private_output:false}));process.exitCode=2;}}
